[package]
name = "modular-esp-idf-kconfig-lib"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
lazy-regex = "3.1.0"
nom = "7.1.3"
nom_locate = { version = "4.2.0", features = ["runtime-dispatch-simd"] }
phf = { version = "0.11.2", features = ["macros"] }
regex = "1.10.2"
